services:
  database:
    image: postgres:17-alpine
    container_name: database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - my-db-data:/var/lib/postgresql/data
    expose:
      - "5432"

  backend:
    build:
      context: ./backend
    container_name: backend-service
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    expose:
      - "3000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    container_name: frontend-app
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  my-db-data: